export enum ErrorType {
    USER_NOT_FOUND = "USER_NOT_FOUND",
    BOOK_NOT_FOUND = "BOOK_NOT_FOUND",
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
    BOOK_ALREADY_EXISTS = "BOOK_ALREADY_EXISTS",
    USER_COULD_NOT_BE_CREATED = "USER_COULD_NOT_BE_CREATED",
}
